name: Create New Branch

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create and push new branch
      env:
        GITHUB_TOKEN: ${{ secrets.PROJECT_TOKEN }}
      run: |
        # Extract project version from Cargo.toml
        PROJECT_VERSION=$(grep '^version' Cargo.toml | sed -E 's/version = "(.*)"/\1/')
        echo "Version extracted: $awsome_variable"
        
        # Configure Git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Create and push new branch
        git checkout -b "$PROJECT_VERSION"
        git push origin "$PROJECT_VERSION"
